export const CRM_DIALER_OPEN_EVENT = 'crm-dialer-open'
export const CRM_DIALER_QUEUE_EVENT = 'crm-dialer-queue'
export const PROSPECTING_DIALER_QUEUE_EVENT = 'prospecting-dialer-queue'
export const PROSPECTING_DIALER_CONTROLS_EVENT = 'prospecting-dialer-controls'
export { PROSPECTING_DIALER_RESET_CALL_CONTEXT_EVENT } from '@/lib/telephony/dialer-session-call-context'
