export const dynamic = 'force-dynamic'

import { NextRequest, NextResponse } from 'next/server'

function escapePdfText(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)')
}

function pageStream(title: string, lines: string[], pageNumber: number, totalPages: number): string {
  const commands = [
    'BT',
    '/F1 10 Tf',
    '72 755 Td',
    `(Saving KC Homebuyers - Test Inspection Report) Tj`,
    '/F1 18 Tf',
    '0 -34 Td',
    `(${escapePdfText(title)}) Tj`,
    '/F1 12 Tf',
  ]

  lines.forEach((line, index) => {
    commands.push(`0 -${index === 0 ? 34 : 20} Td`)
    commands.push(`(${escapePdfText(line)}) Tj`)
  })

  commands.push('/F1 10 Tf')
  commands.push('0 -42 Td')
  commands.push(`(Page ${pageNumber} of ${totalPages}) Tj`)
  commands.push('ET')

  return commands.join('\n')
}

function buildPdf(slug: string): string {
  const pages = [
    {
      title: 'Cover',
      lines: [
        `Deal slug: ${slug}`,
        'Temporary 10-page PDF for buyer-facing report testing.',
        'Purpose: validate the Inspection Reports button, PDF loading,',
        'new-tab behavior, scrolling, and multi-page document rendering.',
        'This file is generated by the test route and is not a real inspection.',
      ],
    },
    {
      title: 'Property Summary',
      lines: [
        'Address: 6509 W 74TH ST, Overland Park, KS 66204',
        'Report type: Test inspection report',
        'Occupancy: Vacant test document',
        'Weather: Clear for testing',
        'Visible areas reviewed: exterior, interior, systems, and safety notes.',
      ],
    },
    {
      title: 'Exterior',
      lines: [
        'Siding: visible wear noted in test summary.',
        'Trim: sample condition note for UI review.',
        'Windows: buyer should be able to scroll this page normally.',
        'Drainage: placeholder observations for multi-page PDF validation.',
        'Exterior recommendation: verify final report upload replaces this file.',
      ],
    },
    {
      title: 'Roof And Attic',
      lines: [
        'Roof covering: test note only.',
        'Flashings: sample observation line.',
        'Gutters: sample observation line.',
        'Attic access: not evaluated in this placeholder document.',
        'Recommendation: use actual inspection photos in production report.',
      ],
    },
    {
      title: 'Foundation And Structure',
      lines: [
        'Foundation: sample condition line.',
        'Framing: sample condition line.',
        'Basement or crawlspace: test report section.',
        'Moisture evidence: placeholder note for visual testing.',
        'Structural recommendation: real inspector notes will appear here.',
      ],
    },
    {
      title: 'Electrical',
      lines: [
        'Panel: sample electrical observation.',
        'Branch wiring: sample electrical observation.',
        'Outlets: sample electrical observation.',
        'Smoke detectors: placeholder safety note.',
        'Recommendation: verify buyer can navigate to page six and back.',
      ],
    },
    {
      title: 'Plumbing',
      lines: [
        'Supply lines: sample plumbing observation.',
        'Drainage: sample plumbing observation.',
        'Water heater: placeholder note.',
        'Fixtures: placeholder note.',
        'Recommendation: actual plumbing report will replace this test content.',
      ],
    },
    {
      title: 'HVAC And Interior',
      lines: [
        'HVAC equipment: sample observation.',
        'Interior walls: sample observation.',
        'Flooring: sample observation.',
        'Ceilings: sample observation.',
        'Recommendation: confirm PDF viewer keeps page text readable on mobile.',
      ],
    },
    {
      title: 'Kitchen, Baths, And Safety',
      lines: [
        'Kitchen: sample finish and fixture observation.',
        'Bathroom: sample finish and fixture observation.',
        'Stairs and rails: sample safety note.',
        'Environmental: placeholder note.',
        'Recommendation: check tap, browser back, and share behavior.',
      ],
    },
    {
      title: 'Summary',
      lines: [
        'This is page ten of the generated test inspection report.',
        'The buyer-facing button should open this PDF inline in a new tab.',
        'Real uploaded reports use deal_pages.inspection_reports and bypass',
        'this temporary fallback for the test slug.',
        'End of test document.',
      ],
    },
  ]

  const totalPages = pages.length
  const streams = pages.map((page, index) => {
    const stream = pageStream(page.title, page.lines, index + 1, totalPages)
    return `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`
  })
  const pageObjectStart = 4
  const contentObjectStart = pageObjectStart + totalPages
  const pageRefs = pages.map((_, index) => `${pageObjectStart + index} 0 R`).join(' ')

  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    `<< /Type /Pages /Kids [${pageRefs}] /Count ${totalPages} >>`,
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
    ...pages.map((_, index) => (
      `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 3 0 R >> >> /Contents ${contentObjectStart + index} 0 R >>`
    )),
    ...streams,
  ]

  let pdf = '%PDF-1.4\n'
  const offsets = [0]
  objects.forEach((object, index) => {
    offsets.push(pdf.length)
    pdf += `${index + 1} 0 obj\n${object}\nendobj\n`
  })

  const xrefOffset = pdf.length
  pdf += `xref\n0 ${objects.length + 1}\n`
  pdf += '0000000000 65535 f \n'
  offsets.slice(1).forEach((offset) => {
    pdf += `${String(offset).padStart(10, '0')} 00000 n \n`
  })
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`

  return pdf
}

export async function GET(
  _request: NextRequest,
  { params }: { params: Promise<{ slug: string }> }
) {
  const { slug } = await params
  const pdf = buildPdf(slug)

  return new NextResponse(pdf, {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `inline; filename="savingkc-${slug}-test-inspection-report.pdf"`,
      'Cache-Control': 'no-store',
    },
  })
}
