-- Audited, fail-closed application boundary for reviewed county source waves.
-- This migration does not change prospect data by itself.

CREATE TABLE IF NOT EXISTS public.county_source_reconciliation_audit (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id uuid NOT NULL,
  wave text NOT NULL,
  source_sha256 text NOT NULL,
  plan_sha256 text NOT NULL,
  prospect_id uuid NOT NULL REFERENCES public.prospects(id),
  source_tab text NOT NULL,
  parcel_fingerprint text,
  address_fingerprint text,
  before_property_class text NOT NULL,
  after_property_class text NOT NULL,
  applied_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT county_source_reconciliation_source_sha_check
    CHECK (source_sha256 ~ '^[a-f0-9]{64}$'),
  CONSTRAINT county_source_reconciliation_plan_sha_check
    CHECK (plan_sha256 ~ '^[a-f0-9]{64}$'),
  CONSTRAINT county_source_reconciliation_class_check
    CHECK (
      before_property_class IN ('residential', 'land', 'unknown')
      AND after_property_class IN ('residential', 'land', 'unknown')
    ),
  CONSTRAINT county_source_reconciliation_unique_target
    UNIQUE (source_sha256, plan_sha256, prospect_id)
);

ALTER TABLE public.county_source_reconciliation_audit ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.county_source_reconciliation_audit
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE public.county_source_reconciliation_audit_id_seq
  FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT ON TABLE public.county_source_reconciliation_audit
  TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.county_source_reconciliation_audit_id_seq
  TO service_role;

CREATE INDEX IF NOT EXISTS idx_county_source_reconciliation_audit_batch
  ON public.county_source_reconciliation_audit (batch_id, prospect_id);

CREATE OR REPLACE FUNCTION public.apply_jackson_county_wave_a_v1(
  p_batch_id uuid,
  p_source_sha256 text,
  p_plan_sha256 text,
  p_rows jsonb
)
RETURNS TABLE (
  batch_id uuid,
  updated_count integer,
  already_applied boolean
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp
SET statement_timeout = '60s'
SET lock_timeout = '5s'
AS $$
DECLARE
  v_count integer;
  v_residential integer;
  v_land integer;
  v_mismatch integer;
  v_updated integer;
  v_prior_batch uuid;
BEGIN
  IF p_batch_id IS NULL
     OR p_source_sha256 !~ '^[a-f0-9]{64}$'
     OR p_plan_sha256 !~ '^[a-f0-9]{64}$'
     OR jsonb_typeof(p_rows) <> 'array' THEN
    RAISE EXCEPTION 'invalid Wave A request';
  END IF;

  CREATE TEMP TABLE wave_a_input ON COMMIT DROP AS
  SELECT
    record.prospect_id,
    record.before_property_class,
    record.after_property_class,
    record.source_tab,
    record.parcel_fingerprint,
    record.address_fingerprint
  FROM jsonb_to_recordset(p_rows) AS record(
    prospect_id uuid,
    before_property_class text,
    after_property_class text,
    source_tab text,
    parcel_fingerprint text,
    address_fingerprint text
  );

  SELECT
    count(*)::integer,
    count(*) FILTER (WHERE after_property_class = 'residential')::integer,
    count(*) FILTER (WHERE after_property_class = 'land')::integer
  INTO v_count, v_residential, v_land
  FROM wave_a_input;

  IF v_count <> 2183 OR v_residential <> 1950 OR v_land <> 233 THEN
    RAISE EXCEPTION 'Wave A source count drift: total %, residential %, land %',
      v_count, v_residential, v_land;
  END IF;

  SELECT count(*)::integer - count(DISTINCT prospect_id)::integer
  INTO v_mismatch
  FROM wave_a_input;
  IF v_mismatch <> 0 THEN
    RAISE EXCEPTION 'Wave A contains duplicate prospect targets';
  END IF;

  SELECT audit.batch_id
  INTO v_prior_batch
  FROM public.county_source_reconciliation_audit AS audit
  WHERE audit.wave = 'jackson_property_class_wave_a'
    AND audit.source_sha256 = p_source_sha256
    AND audit.plan_sha256 = p_plan_sha256
  ORDER BY audit.batch_id
  LIMIT 1;

  IF v_prior_batch IS NOT NULL THEN
    SELECT count(*)::integer
    INTO v_mismatch
    FROM wave_a_input AS input
    JOIN public.prospects AS prospect ON prospect.id = input.prospect_id
    WHERE prospect.property_class = input.after_property_class;

    IF v_mismatch <> 2183 OR EXISTS (
      SELECT input.prospect_id
      FROM wave_a_input AS input
      EXCEPT
      SELECT audit.prospect_id
      FROM public.county_source_reconciliation_audit AS audit
      WHERE audit.wave = 'jackson_property_class_wave_a'
        AND audit.source_sha256 = p_source_sha256
        AND audit.plan_sha256 = p_plan_sha256
    ) OR EXISTS (
      SELECT audit.prospect_id
      FROM public.county_source_reconciliation_audit AS audit
      WHERE audit.wave = 'jackson_property_class_wave_a'
        AND audit.source_sha256 = p_source_sha256
        AND audit.plan_sha256 = p_plan_sha256
      EXCEPT
      SELECT input.prospect_id
      FROM wave_a_input AS input
    ) OR (
      SELECT count(*)
      FROM public.county_source_reconciliation_audit AS audit
      WHERE audit.wave = 'jackson_property_class_wave_a'
        AND audit.source_sha256 = p_source_sha256
        AND audit.plan_sha256 = p_plan_sha256
    ) <> 2183 THEN
      RAISE EXCEPTION 'Wave A prior audit does not match current prospect state';
    END IF;

    RETURN QUERY SELECT v_prior_batch, 0, true;
    RETURN;
  END IF;

  PERFORM 1
  FROM public.prospects AS prospect
  JOIN wave_a_input AS input ON input.prospect_id = prospect.id
  ORDER BY prospect.id
  FOR UPDATE OF prospect;

  SELECT count(*)::integer
  INTO v_mismatch
  FROM wave_a_input AS input
  LEFT JOIN public.prospects AS prospect ON prospect.id = input.prospect_id
  WHERE prospect.id IS NULL
     OR regexp_replace(
       lower(trim(coalesce(prospect.county, ''))),
       '[[:space:]]+county$',
       ''
     ) <> 'jackson'
     OR prospect.property_class IS DISTINCT FROM input.before_property_class
     OR input.before_property_class = input.after_property_class
     OR input.after_property_class NOT IN ('residential', 'land')
     OR input.source_tab NOT IN ('2 Yr. Only', '3 Yrs (+)', 'Land')
     OR NOT (
       coalesce(input.parcel_fingerprint, '') ~ '^[a-f0-9]{32}$'
       OR coalesce(input.address_fingerprint, '') ~ '^[a-f0-9]{32}$'
     );

  IF v_mismatch <> 0 THEN
    RAISE EXCEPTION 'Wave A production precondition drift on % targets', v_mismatch;
  END IF;

  INSERT INTO public.county_source_reconciliation_audit (
    batch_id,
    wave,
    source_sha256,
    plan_sha256,
    prospect_id,
    source_tab,
    parcel_fingerprint,
    address_fingerprint,
    before_property_class,
    after_property_class
  )
  SELECT
    p_batch_id,
    'jackson_property_class_wave_a',
    p_source_sha256,
    p_plan_sha256,
    input.prospect_id,
    input.source_tab,
    input.parcel_fingerprint,
    input.address_fingerprint,
    input.before_property_class,
    input.after_property_class
  FROM wave_a_input AS input
  ORDER BY input.prospect_id;

  UPDATE public.prospects AS prospect
  SET property_class = input.after_property_class
  FROM wave_a_input AS input
  WHERE prospect.id = input.prospect_id;
  GET DIAGNOSTICS v_updated = ROW_COUNT;

  IF v_updated <> 2183 THEN
    RAISE EXCEPTION 'Wave A updated % rows instead of 2183', v_updated;
  END IF;

  RETURN QUERY SELECT p_batch_id, v_updated, false;
END
$$;

REVOKE ALL ON FUNCTION public.apply_jackson_county_wave_a_v1(uuid, text, text, jsonb)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.apply_jackson_county_wave_a_v1(uuid, text, text, jsonb)
  TO service_role;

COMMENT ON TABLE public.county_source_reconciliation_audit IS
  'Immutable before/after evidence for reviewed county source corrections; contains fingerprints, not source PII.';
COMMENT ON FUNCTION public.apply_jackson_county_wave_a_v1(uuid, text, text, jsonb) IS
  'Fail-closed Jackson County Wave A property-class correction. It cannot create leads, campaigns, calls, or messages.';
