-- Frozen campaign publication spine. No rows created here can dispatch email.
DO $$ BEGIN
  IF to_regclass('public.em_workspaces') IS NULL OR to_regclass('public.em_addresses') IS NULL OR to_regclass('public.em_parties') IS NULL THEN RAISE EXCEPTION 'email campaigns require workspace and identity tables'; END IF;
END $$;
CREATE TABLE public.em_audiences (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL REFERENCES public.em_workspaces(id), name text NOT NULL CHECK(char_length(trim(name)) BETWEEN 1 AND 120), program text NOT NULL CHECK(program IN ('seller_outreach','seller_nurture','buyer_marketing')), state text NOT NULL DEFAULT 'draft' CHECK(state IN ('draft','processing','ready','archived')), revision bigint NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(workspace_id,id));
CREATE TABLE public.em_audience_snapshots (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL, audience_id uuid NOT NULL, source_revision bigint NOT NULL, content_hash text NOT NULL, row_count integer NOT NULL CHECK(row_count >= 0), eligible_count integer NOT NULL CHECK(eligible_count >= 0), created_by uuid, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(workspace_id,id), UNIQUE(audience_id,source_revision), FOREIGN KEY(workspace_id,audience_id) REFERENCES public.em_audiences(workspace_id,id));
CREATE TABLE public.em_snapshot_rows (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL, snapshot_id uuid NOT NULL, party_id uuid, address_id uuid NOT NULL, property_ref text, eligibility text NOT NULL CHECK(eligibility IN ('eligible','excluded','needs_review')), reason_codes text[] NOT NULL DEFAULT '{}', evidence_hash text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE NULLS NOT DISTINCT(workspace_id,snapshot_id,address_id,property_ref), FOREIGN KEY(workspace_id,snapshot_id) REFERENCES public.em_audience_snapshots(workspace_id,id), FOREIGN KEY(workspace_id,address_id) REFERENCES public.em_addresses(workspace_id,id), FOREIGN KEY(workspace_id,party_id) REFERENCES public.em_parties(workspace_id,id));
CREATE TABLE public.em_campaigns (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL REFERENCES public.em_workspaces(id), name text NOT NULL CHECK(char_length(trim(name)) BETWEEN 1 AND 120), program text NOT NULL CHECK(program IN ('seller_outreach','seller_nurture','buyer_marketing')), state text NOT NULL DEFAULT 'draft' CHECK(state IN ('draft','scheduled','active','paused','completed','archived')), draft_config jsonb NOT NULL DEFAULT '{}'::jsonb CHECK(jsonb_typeof(draft_config)='object'), active_version_id uuid, owner_id uuid NOT NULL, revision bigint NOT NULL DEFAULT 0, archived_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(workspace_id,id));
CREATE TABLE public.em_campaign_versions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL, campaign_id uuid NOT NULL, version_number integer NOT NULL CHECK(version_number > 0), snapshot_id uuid NOT NULL, playbook_version_id uuid NOT NULL, config jsonb NOT NULL CHECK(jsonb_typeof(config)='object'), content_hash text NOT NULL, review_hash text NOT NULL, published_by uuid NOT NULL, published_at timestamptz NOT NULL DEFAULT now(), UNIQUE(campaign_id,version_number), UNIQUE(workspace_id,id), FOREIGN KEY(workspace_id,campaign_id) REFERENCES public.em_campaigns(workspace_id,id), FOREIGN KEY(workspace_id,snapshot_id) REFERENCES public.em_audience_snapshots(workspace_id,id));
ALTER TABLE public.em_campaigns ADD CONSTRAINT em_campaigns_active_version_fk FOREIGN KEY(workspace_id,active_version_id) REFERENCES public.em_campaign_versions(workspace_id,id) DEFERRABLE INITIALLY DEFERRED;
CREATE TABLE public.em_enrollments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL, campaign_id uuid NOT NULL, campaign_version_id uuid NOT NULL, party_id uuid, address_id uuid NOT NULL, property_ref text, state text NOT NULL DEFAULT 'queued' CHECK(state IN ('queued','waiting_reply','completed','replied','suppressed','held','failed')), created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(workspace_id,id), UNIQUE(campaign_version_id,address_id), FOREIGN KEY(workspace_id,campaign_id) REFERENCES public.em_campaigns(workspace_id,id), FOREIGN KEY(workspace_id,campaign_version_id) REFERENCES public.em_campaign_versions(workspace_id,id), FOREIGN KEY(workspace_id,address_id) REFERENCES public.em_addresses(workspace_id,id), FOREIGN KEY(workspace_id,party_id) REFERENCES public.em_parties(workspace_id,id));
CREATE UNIQUE INDEX em_one_active_address ON public.em_enrollments(workspace_id,address_id) WHERE state IN ('queued','waiting_reply','held');
ALTER TABLE public.em_audiences ENABLE ROW LEVEL SECURITY; ALTER TABLE public.em_audience_snapshots ENABLE ROW LEVEL SECURITY; ALTER TABLE public.em_snapshot_rows ENABLE ROW LEVEL SECURITY; ALTER TABLE public.em_campaigns ENABLE ROW LEVEL SECURITY; ALTER TABLE public.em_campaign_versions ENABLE ROW LEVEL SECURITY; ALTER TABLE public.em_enrollments ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.em_audiences,public.em_audience_snapshots,public.em_snapshot_rows,public.em_campaigns,public.em_campaign_versions,public.em_enrollments FROM PUBLIC,anon,authenticated;
GRANT ALL ON TABLE public.em_audiences,public.em_audience_snapshots,public.em_snapshot_rows,public.em_campaigns,public.em_campaign_versions,public.em_enrollments TO service_role;
